language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.5
# - 5.6
 - 7.0

env:
 global:
  - IGNORE_PATHS=sdk/,pix/
  - IGNORE_NAMES=jquery*,styles.css
 matrix:
#  - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
#  - DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE

matrix:
  exclude:
  - env: DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
    php: 5.5
  - env: DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
    php: 5.5

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
#  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
#  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
#  - moodle-plugin-ci jshint
  - moodle-plugin-ci validate
#  - moodle-plugin-ci phpunit
#  - moodle-plugin-ci behat